version: '3.3'

services:
    api-gateway:
        build:
            context: .
            dockerfile: Dockerfile-gateway
        ports:
            - "8080:8080"

    service-registry:
            build:
                context: .
                dockerfile: Dockerfile-registry
            ports:
                - "8081:8080"

    simple-service:
            build:
                context: .
                dockerfile: Dockerfile-service
            ports:
                - "8082:8080"

